### PR TITLE
fix: limit chip list tags

### PR DESCRIPTION
**Pull request by nlewis84**
- chore: bump version of data-connector-postgres and limit number of tags in chip list
- chore: update env with new rock token

@redreceipt All their Rock tags where showing up in the chip list, many did not have associated content items that were service opportunities. We had implemented these limit changes in the cluster, but I didn't see a clear path for upgrading to those packages. I instead override the resolver for Content Items and the getContentTags method on the datasource for Content Items. 

Here's a video of the newly filtered chip list:

https://user-images.githubusercontent.com/72768221/167887722-e63dc99f-3c93-42a6-9283-4685cc3529e6.mp4

I did not see any adverse effects from this. Does it look like I missed anything? Oh, I also updated the Rock Token for local testing....this was updated in Heroku, but not in the `.env.shared`.

### CODE REVIEW

**Comment by nlewis84** [comment]
@redreceipt You lost me on that one. I tried updating the package to v2, but the limit change was not there. I'm not sure how to push to v2.

**Comment by redreceipt** [comment]
Yea we probably need to cherry pick that commit into v2 and then cut a release. We could pair this afternoon and I could show you how?

**Comment by nlewis84** [comment]
Yeah, I'll grab a time with you

**Comment by nlewis84** [comment]
Tested this out with the new v2 branch. Had to grab one more package that was missing as a dependency, but otherwise works the same as previous implementation.

https://user-images.githubusercontent.com/72768221/167928952-50f19c8a-2231-47d4-9cfb-15ef7ea80c9c.mp4

**Pull request merged**
